{% set name = "rpcq" %}
{% set version = "3.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d4695048f874aa255764336fa1965f6fc1ea001a31e28681bbbef708cac531e1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python  >=3.6.0
    - pip
  run:
    - python
    - msgpack-python  >=0.6,<1.0
    - python-rapidjson
    - pyzmq  >=17
    - ruamel.yaml

test:
  imports:
    - rpcq

about:
  home: https://www.rigetti.com
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: The RPC framework and message specification for Rigetti QCS
  dev_url: https://github.com/rigetticomputing/rpcq

extra:
  recipe-maintainers:
    - jmackeyrigetti
    - kilimanjaro
    - notmgsk
