appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: wzjhmh+rhV83D+s8VmRz0U4nZUBQyYvv7Cgglqk5rJGLJCDqQ4lF28eMgMGGBTw3AW8HX4kl7HfQhPNgYOCR/k7JG/cwQjDt4hcPgq31tBXK3AUM1t6gY7tCgzjtPnblWKlpTlOMkBj2mmtwi8uLuoExKZLiG9YYB015KO0+O0U87R2SQOe9oAUU1UQv2kvK2HohvNQv5vct8sYNSZf6BkzMzgC42WtWYTy9X9R8jquoAVojy2XukJmvizzuKgQQn5IYYhek/IP16g+ildanKLtnVHlL70Ab5ZQJ9spqBCmMhf7Fm0vGXB09Vt84xc98sHeXPGumVXnad7CrXZTlqbHzrhZ3jCNgDOl0b2RtgF3ANkXuYdQDG0BTPVT1Dwh6iuWBp3Qta9gRyufxC9b0ZjIHAoSW594Tr+QwlGt6eyE6G9Wb/wAgc2TY7deRvVmXmh8Hqwg2/z6hPNiTRp74kq9y1MecdinxTRm4HD+EMFOtbib6dVh8WUoePNsCaAIuCJnpCzZyHsDe+gZwz8XHxc1ndwmBWiInt8L1pKZ74HadwJrfmg+zVIWAEVX3okm27jEGVdIL0qSCMuZ4rHQn695uTQMN1CWASvoL8GiBB02IsMJ0jZ57YjhrZhbc4NlC9qfO9mbQ8SW/J4Mq1i/LUo+eAqKJ4HSsOfFklPwKVaE=}
